apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: domains.dns.deinstapel.de
spec:
  conversion:
    strategy: None
  group: dns.deinstapel.de
  names:
    kind: Domain
    listKind: DomainList
    plural: domains
    singular: domain
  scope: Cluster
  subresources:
    status: {}
  version: v1
  versions:
    - name: v1
      served: true
      storage: true