apiVersion: apps/v1
kind: Deployment
metadata:
  name: domainik
  namespace: operators
  labels:
    app.kubernetes.io/name: domainik
    app.kubernetes.io/instance: domainik

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: domainik
      app.kubernetes.io/instance: domainik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: domainik
        app.kubernetes.io/instance: domainik
    spec:
      serviceAccountName: domainik
      containers:
        - name: domainik
          image: deinstapel/domainik:0.1.0

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: domainik
  namespace: operators

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: domainik
rules:
  - apiGroups: [""] #
    resources: ["nodes", "secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["dns.deinstapel.de"]
    resources: ["domains", "domainmanagers"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: domainik
subjects:
  - kind: ServiceAccount
    name: domainik
    namespace: operators
roleRef:
  kind: ClusterRole
  name: domainik
  apiGroup: rbac.authorization.k8s.io